// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrJYXInPBBdmk5BwvN_ae-LIubjs2rJBw',
    appId: '1:61811328937:web:15fe1e4980253240e966b8',
    messagingSenderId: '61811328937',
    projectId: 'attendance-application-aab7a',
    authDomain: 'attendance-application-aab7a.firebaseapp.com',
    storageBucket: 'attendance-application-aab7a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkNRX7-o0_WWXFqSVWYJqVDzbsxNzba-I',
    appId: '1:61811328937:android:876f59aff8010e06e966b8',
    messagingSenderId: '61811328937',
    projectId: 'attendance-application-aab7a',
    storageBucket: 'attendance-application-aab7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADHo5f8jBuftDrvE74yqqTgu75n8DhBkE',
    appId: '1:61811328937:ios:8344da7274bf7319e966b8',
    messagingSenderId: '61811328937',
    projectId: 'attendance-application-aab7a',
    storageBucket: 'attendance-application-aab7a.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADHo5f8jBuftDrvE74yqqTgu75n8DhBkE',
    appId: '1:61811328937:ios:8344da7274bf7319e966b8',
    messagingSenderId: '61811328937',
    projectId: 'attendance-application-aab7a',
    storageBucket: 'attendance-application-aab7a.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrJYXInPBBdmk5BwvN_ae-LIubjs2rJBw',
    appId: '1:61811328937:web:9aeec77c477e14b7e966b8',
    messagingSenderId: '61811328937',
    projectId: 'attendance-application-aab7a',
    authDomain: 'attendance-application-aab7a.firebaseapp.com',
    storageBucket: 'attendance-application-aab7a.firebasestorage.app',
  );
}
